dist: precise
sudo: required

language: php

matrix:
  include:
  - env: PRECISE=deprecated
    group: deprecated-2017Q1
    php: 5.5
  - env: PRECISE=new
    group: stable
    php: 5.5
    
install: true

script:
- echo "$PATH"
- which php
- ls /usr/bin/php
- /usr/bin/php -r 'echo "a";'
- if [[ "$PRECISE" == "new" ]]; then /usr/bin/php; fi
